#pragma once

#include "corekit/api/factory.hpp"
#include "corekit/api/i_component.hpp"
#include "corekit/api/status.hpp"
#include "corekit/api/unique_handle.hpp"
#include "corekit/api/version.hpp"
#include "corekit/concurrent/containers.hpp"
#include "corekit/concurrent/i_map.hpp"
#include "corekit/concurrent/i_queue.hpp"
#include "corekit/concurrent/i_ring_buffer.hpp"
#include "corekit/concurrent/i_set.hpp"
#include "corekit/ipc/i_channel.hpp"
#include "corekit/json/i_json.hpp"
#include "corekit/log/ilog_manager.hpp"
#include "corekit/log/log_macros.hpp"
#include "corekit/log/log_types.hpp"
#include "corekit/io/i_file.hpp"
#include "corekit/memory/i_global_allocator.hpp"
#include "corekit/memory/iallocator.hpp"
#include "corekit/memory/i_memory_pool.hpp"
#include "corekit/memory/i_object_pool.hpp"
#include "corekit/memory/system_pool.hpp"
#include "corekit/task/executor_helpers.hpp"
#include "corekit/task/iexecutor.hpp"
#include "corekit/task/i_task_graph.hpp"
#include "corekit/xml/i_xml_doc.hpp"

